# Generated by Django 6.0.2 on 2026-02-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isMale', models.BooleanField()),
                ('grit', models.IntegerField(default=1)),
                ('rice', models.IntegerField(default=1)),
            ],
        ),
    ]
