# Generated by Django 6.0.2 on 2026-02-04 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincharacter',
            old_name='isMale',
            new_name='is_male',
        ),
        migrations.RemoveField(
            model_name='maincharacter',
            name='grit',
        ),
        migrations.RemoveField(
            model_name='maincharacter',
            name='rice',
        ),
        migrations.AddField(
            model_name='maincharacter',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maincharacter',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grit', models.IntegerField(default=1)),
                ('rice', models.IntegerField(default=0)),
                ('current_cycle', models.IntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.maincharacter')),
            ],
        ),
    ]
