# Generated by Django 6.0.2 on 2026-02-05 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_rename_ismale_maincharacter_is_male_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='core_app.maincharacter'),
        ),
        migrations.AlterField(
            model_name='maincharacter',
            name='is_male',
            field=models.BooleanField(default=True),
        ),
    ]
