# Generated by Django 6.0.2 on 2026-03-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_gamesession_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='hazard_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='story_log',
            field=models.TextField(default='The journey begins in the ashes of Kyoto...'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='rice',
            field=models.IntegerField(default=6),
        ),
    ]
