# Generated by Django 6.0.2 on 2026-03-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_gamesession_hazard_level_gamesession_story_log_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='hazard_level',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='fire_danger',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='segments_left',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='grit',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='rice',
            field=models.IntegerField(default=5),
        ),
    ]
