# Generated by Django 6.0.2 on 2026-03-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_remove_gamesession_hazard_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='current_region',
            field=models.CharField(default='palace_gates', max_length=50),
        ),
    ]
