# Generated by Django 6.0.2 on 2026-03-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_gamesession_current_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='daily_actions_buffer',
            field=models.JSONField(default=list),
        ),
    ]
