# Generated by Django 6.0.2 on 2026-03-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_gamesession_daily_actions_buffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='met_fox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='monk_encounters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='monk_rice_donated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='pending_event',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
    ]
