# Generated by Django 6.0.2 on 2026-04-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_gamesession_met_fox_gamesession_monk_encounters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='has_monastery_key',
            field=models.BooleanField(default=False),
        ),
    ]
