# Generated by Django 6.0.2 on 2026-04-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_gamesession_has_monastery_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincharacter',
            name='cause_of_death',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maincharacter',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
    ]
