# Generated by Django 6.0.2 on 2026-04-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0010_maincharacter_cause_of_death_maincharacter_is_dead'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='has_comb',
            field=models.BooleanField(default=False),
        ),
    ]
